### ISSUE TITLE
Nuget package?

### ISSUE THREAD

**Issue by mcintyre321** [nathanpjones/randomColorSharped#1]
Any chance you could put this on Nuget?

thanks

**Comment by mrchief** [comment]
I can send a PR for this, if you're interested...

**Comment by nathanpjones** [comment]
Please do. Thanks!

Nathan Jones

**Comment by nathanpjones** [comment]
Okay, I've published a separte package for [WinForms](https://www.nuget.org/packages/randomColorSharped.Forms/) and [WPF](https://www.nuget.org/packages/randomColorSharped.WPF/). Repo push to come shortly.

**Comment by mrchief** [comment]
Its just a suggestion - While packaging I thought about it and that is why I packaged only the library (and not the apps). I think you don't have to tie yourself up with WPF or WinForms. The color producing library is generic enough to be used in any type of application, windows/web alike. Only the sample app you have needs ties with WPF/WinForms. 

I'm afraid that the name WPF and Winforms (in the nuget package) will dissuade Web and other devs to look elsewhere while this library will do a perfectly fine job.

I'd propose the following:

`randomColorSharped` - Core package that produces random color
`randomColorSharped.Sample.Winform` - Sample using above core package and Winforms
`randomColorSharped.Sample.Wpf` - Sample using above core package and WPF

Makes sense?

**Comment by nathanpjones** [comment]
Well, the package has to have some sort of structured return type for the color. That's what I tried to convey in the change to the readme. I think those developing in ASP.NET should be sophisticated enough to know what to choose--either this or the original project's javascript version.

**Comment by mrchief** [comment]
Oh yeah, forgot that [lousy mess](http://stackoverflow.com/a/17265769/244353) created by MS!

**Comment by mcintyre321** [comment]
There's a project called [Splat](https://github.com/paulcbetts/splat) with a portable Color library in it. You might be able to ditch/shrink the Winform/WPF/WinUI projects if you targeted that.
