### ISSUE TITLE
Set PlatformTarget=AnyCPU for Platform=AnyCPU

### ISSUE THREAD

**Issue by seangenabe** [nathanpjones/randomColorSharped#3]
On both WPF and WinForms projects, I have noticed that the `PlatformTarget` for `Platform`==`AnyCPU` is set to `x86`. Please consider setting these to `AnyCPU` instead.

Edit: I realize that there is only an x86 configuration in the solution level. Please consider supporting AnyCPU.

**Comment by nathanpjones** [comment]
What kind of problems is this causing for you?

**Comment by dhaddad355** [comment]
If using with IIS > 7 32 bit applications are disabled by default.  The application will throw "System.BadImageFormatException: Could not load file or assembly 'Random Color Generator.Forms' or one of its dependencies.", you should support AnyCPU

**Comment by mdczaplicki** [comment]
Damn, that's my problem too. As for me library is unfortunately useless. :(

Not useless, I have managed to change to AnyCPU, compile and now works.
