### ISSUE TITLE
Update URL in readme

### ISSUE THREAD

**Issue by seangenabe** [nathanpjones/randomColorSharped#4]
The link to randomColor http://llllll.li/randomColor/ doesn't display pertinent information anymore. I think the new URL might be https://randomcolor.lllllllllllllllll.com/ ? Or maybe just use the GitHub repo page https://github.com/davidmerfield/randomColor ? I don't know if this is actually the original source repo.

**Comment by Danghor** [comment]
The current link leads to scamming and advertising websites. It should really be fixed!

**Comment by nathanpjones** [comment]
@Danghor Thanks for the heads up
